export enum TitleMessageEnum {
    ConfirmTitle="Confirm",
    WarnningTitle="Warnning",
    ErrorTitle="Error",
    InfoTitle="Attention",
}

export enum BodyMessageEnum {

    AddedSuccessfullyMessage="Added Successfully",
    BackupSuccessfullyMessage="Backup Successfully",
    ModifiedSuccessfullyMessage="Modified Successfully",
    DeletedSuccessfullyMessage="Deleted Successfully",
    UnExpectedErorrMessage="UnExpected Erorr",
    NameUsedBeforeMessage="Name Used Before",
    InvalidDataMessage="Invalid Data",
    UserNameUsedBeforeMessage="User Name Used Before",
    NotFoundMessage="Not Found",
    HaveRowsMessage="Have Rows",
    SomeInsertedOtherNotMessage="Some Inserted Other Not",
    SomeUpdatedOtherNotMessage="Some Updated Other Not",
    SomeDeletedOtherNotMessage="Some Deleted Other Not",
    AllHaveRowsMessage="All Have Rows",
    AllInsertedBeforeMessage="All Inserted Before",
    RowInsertedBeforeMessage="Row Inserted Before",
    UpdateDeletedBeforeMessage="Update Deleted Before",
    DeletedDeletedBeforeMessage="Deleted Deleted Before",
    UnExpectedErorrOnPageMessage="UnExpected Erorr On Page",
    EmailUsedBeforeMessage="Email Used Before",
    ConfirmedSuccessFullyMessage="Confirmed Success Fully",
    NameIsRequiredMessage="Name Is Required",
    EmailIsRequiredMessage="Email Is Required",
    FromKMRequiredMessage="From KM Required",
    ToKMIsRequiredMessage="To KM Is Required",
    ValueRequiredMessage="Value Required",
    ExtraKMIsRequiredMessage="Extra KM Is Required",
    ExtraValueIsRequiredMessage="Extra Value Is Required",
    PasswordIsRequiredMessage="Password Is Required",
    PhoneNumberIsRequiredMessage="Phone Number Is Required",
    RoleIsRequiredMessage="Role Is Required",
    StartDateValidIsRequiredMessage="Start Date Valid Is Required",
    AreaIsRequiredMessage="Area Is Required",
    CountryIsRequiredMessage="Country Is Required",
    RegionIsRequiredMessage="Region Is Required"
}
