export enum OrderStateEnum {
  Created = 9,
  FailedToAssign = 18,
  Assigned = 27,
  Accepted = 36,
  CaptainRejected = 45,
  StartRide = 54,
  ReachedShop = 63,
  OrderPicked = 72,
  Shipped = 81,
  ReachedLocation = 90,
  CustomerRejected = 99,
  CustomerChangeLocation = 108,
  Delivered = 117,
  Canceled = 126,
}
